
version: '3.7'

services:

  ws-server:
    image: ws-server:latest
    container_name: ws-server
    hostname: ws-server
    build:
      context: ./
      dockerfile: Docker/ws-server.Dockerfile
    ports:
      - 8080:8080

  ws-client:
    image: ws-client:latest
    container_name: ws-client
    hostname: ws-client
    build:
      context: ./
      dockerfile: Docker/ws-client.Dockerfile

  ws-server-node:
    image: ws-server-node:latest
    container_name: ws-server-node
    hostname: ws-server-node
    build:
      context: ./ws-server-node/
      dockerfile: ../Docker/ws-server-node.Dockerfile
    ports:
      - 8081:8080

  ws-web:
    image: ws-web:latest
    container_name: ws-web
    hostname: ws-web
    build:
      context: ./ws-web/
      dockerfile: ../Docker/ws-web.Dockerfile
    ports:
      - 80:80

