
version: '3.7'

services:

  ws-server:
    image: ws-server:latest
    container_name: ws-server
    hostname: ws-server
    build:
      context: ./
      dockerfile: Docker/ws-server.Dockerfile
    ports:
      - 8080:8080

  ws-client:
    image: ws-client:latest
    container_name: ws-client
    hostname: ws-client
    build:
      context: ./
      dockerfile: Docker/ws-client.Dockerfile
    depends_on: 
      - ws-server
    environment: 
      - FILE=input.json
    volumes:
      - ./ws-client:/ws-client
